### ISSUE TITLE
配信データの「台風の暴風域に入る確率（Ｒ２）」について

### ISSUE THREAD

**Issue by maikuradentetu** [pdmdss/doc.dmdata.jp#2]
概要の/Report/Control/Titleが、本来記載されるべき「台風の暴風域に入る確率」なのが「台風の暴風域に入る確率（Ｒ２）」になっています。

**Comment by soshi1822** [comment]
確認が遅くなりました、確かにそうの通りですので修正します

**Comment by soshi1822** [comment]
fix: [[`2b43c59`](https://github.com/pdmdss/doc.dmdata.jp/commit/2b43c59a15a779ff27ea74cdbca1b17a35ea254a)]
